addons:
  ssh_known_hosts: 37.140.199.148
before_deploy:
- openssl aes-256-cbc -K $encrypted_e5e049ce4472_key -iv $encrypted_e5e049ce4472_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
