language: node_js
node_js:
  - "10.15.2"
deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_a447902e96e3_key -iv $encrypted_a447902e96e3_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
